let user=null,csrf='',products=[],settings={},orders=[],summary={},page=0,hasMore=false,search='',quote=null,checkoutInput=null,currentOrder=null,busy=false;
let cart;try{cart=JSON.parse(localStorage.getItem('aero-cart')||'[]');if(!Array.isArray(cart))cart=[];}catch{cart=[];}
cart=cart.filter(x=>typeof x.id==='string'&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=99);
const app=document.querySelector('#app'),modal=document.querySelector('#modal');
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=cents=>'$'+(Number(cents)/100).toFixed(2),date=ms=>new Date(ms).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const badge=status=>`<span class="badge ${status.toLowerCase().replaceAll(' ','-')}">${escape(status)}</span>`;
const item=id=>products.find(p=>p.id===id),count=()=>cart.reduce((n,l)=>n+l.quantity,0);
const button=(label,action,id='',kind='')=>`<button class="btn ${kind}" data-action="${action}" ${id?`data-id="${escape(id)}"`:''}>${label}</button>`;
let toastTimer;
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),5500);}
async function api(path,options={}){const response=await fetch('/api'+path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,...options.headers},...(options.body?{body:JSON.stringify(options.body)}:{})});let data;try{data=await response.json();}catch{throw new Error('The store service is unavailable. Please try again.');}if(!response.ok){if(response.status===401&&!path.includes('/auth/login'))user=null;throw new Error(data.error||'Please try again.');}return data;}
async function refreshSession(){const session=await api('/me');user=session.user;csrf=session.csrf;}
function routeName(){return location.hash.split('?')[0].replace(/^#\//,'')||'shop';}
const heading=(eyebrow,title,description)=>`<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="subtitle">${description}</p></div></div>`;
function shell(content,portal=false){const strip=!settings.checkoutReady?'<div class="store-strip">Online ordering is not open yet.</div>':settings.paypal&&settings.paypalMode==='sandbox'?'<div class="store-strip">PayPal test mode · PayPal payments use sandbox accounts.</div>':'';const header=`<header class="store-header"><a href="#/shop" aria-label="Aero Aminos home"><img class="brand" src="/logo.png" alt="Aero Aminos"></a><nav class="store-links" aria-label="Store navigation"><a class="desktop-link" href="#/shop">Collection</a><a href="#/cart">Bag (${count()})</a><a href="${user?'#/overview':'#/login'}">${user?'Account':'Sign in'}</a></nav></header>`;
 if(!portal)return strip+header+`<main id="main" class="store-main" tabindex="-1">${content}${footer()}</main>`;
 const isOwner=user?.role==='owner',route=routeName(),links=[['overview','Overview'],['orders',isOwner?'Orders':'My orders'],...(isOwner?[['inventory','Product collection'],['activity','Activity'],['setup','Store setup']]:[]),['account','Account']];
 return strip+`<div class="shell"><aside class="sidebar"><a href="#/shop"><img class="brand" src="/logo.png" alt="Aero Aminos"></a><p class="portal-label">${isOwner?'Owner portal':'Your account'}</p><nav class="nav" aria-label="Account navigation">${links.map(([url,label])=>`<a href="#/${url}" class="${route===url?'active':''}" ${route===url?'aria-current="page"':''}>${label}</a>`).join('')}<a href="#/shop">Shop collection</a></nav><div class="side-bottom"><p class="side-note">A clear view of every order.</p><div class="identity"><span class="avatar">${escape(user.name.slice(0,2).toUpperCase())}</span><div><strong>${escape(user.name)}</strong><small>${isOwner?'Owner':'Customer'}</small></div><button data-action="logout" aria-label="Sign out">↪</button></div></div></aside><div class="workspace"><header class="topbar"><span>${isOwner?'Owner portal':'My account'}</span><a href="#/shop">Shop collection</a></header><main id="main" class="main" tabindex="-1">${content}${footer()}</main></div></div>`;
}
function footer(){return `<footer class="footer"><span>AERO AMINOS</span><span>${settings.supportEmail?`<a href="mailto:${escape(settings.supportEmail)}">Contact support</a>`:'Support details will be available before launch.'}</span></footer>`;}
function shop(){const filtered=products.filter(p=>`${p.name} ${p.strength}`.toLowerCase().includes(search.toLowerCase()));return `<div class="store-hero"><div><p class="eyebrow">AERO AMINOS / PRODUCT COLLECTION</p><h1>The collection.<br><em>On your terms.</em></h1><p class="subtitle">Explore the full collection. One-time purchases.</p></div><p>Sign in to manage your orders and follow their progress.</p></div><div class="hero-rule"></div><div class="toolbar" style="padding:0 0 24px;border:0"><label class="sr-only" for="product-search">Search products</label><input id="product-search" class="input" type="search" placeholder="Search the collection" value="${escape(search)}"><span class="small muted">${products.length} products</span></div><div class="product-grid" id="product-results">${productCards(filtered)}</div>`;}
function productCards(list){return list.length?list.map(p=>`<article class="product-card"><div class="product-code">${p.id}</div><h2>${escape(p.name)}</h2><p>${escape(p.strength)}</p><div class="product-buy"><span class="money">${money(p.price)}</span><button class="btn" data-action="add" data-id="${p.id}" ${p.stock===0?'disabled':''}>${p.stock===0?'Out of stock':'Add to bag'}</button></div></article>`).join(''):'<div class="empty">No products match your search.</div>';}
function cartPage(){const lines=cart.filter(l=>item(l.id));const subtotal=lines.reduce((n,l)=>n+item(l.id).price*l.quantity,0);return heading('YOUR SELECTION','Your bag.','Review your products before checkout.')+(lines.length?`<div class="cart-layout"><section class="panel">${lines.map(l=>{const p=item(l.id);return `<div class="cart-line"><div><h3>${escape(p.name)}</h3><p>${p.strength} · ${money(p.price)} each</p></div><div class="quantity-control"><label class="sr-only" for="qty-${p.id}">${escape(p.name)} quantity</label><input id="qty-${p.id}" class="input qty" type="number" min="1" max="99" value="${l.quantity}" data-quantity="${p.id}"><span class="money">${money(p.price*l.quantity)}</span><button class="text-btn" data-action="remove" data-id="${p.id}" aria-label="Remove ${escape(p.name)}">Remove</button></div></div>`;}).join('')}</section><section class="panel"><div class="panel-head"><h2>Order summary</h2></div><div class="panel-body"><div class="totals"><div><span>Products</span><span>${money(subtotal)}</span></div><div><span>Shipping and tax</span><span>At checkout</span></div></div><p class="policy-note">Each item is a one-time purchase. There are no recurring charges.</p>${settings.checkoutReady?`<a class="btn primary full" href="${user?'#/checkout':'#/login'}">${user?'Continue to checkout':'Sign in to checkout'}</a>`:'<div class="notice neutral"><p>Online ordering opens once stock, delivery and payment setup are complete.</p></div>'}</div></section></div>`:`<div class="empty"><h2>Your bag is empty.</h2><p class="muted">Explore the collection to add products.</p><a class="btn primary" href="#/shop">View collection</a></div>`);}
function input(name,label,type='text',value='',required=true){return `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" class="input" type="${type}" value="${escape(value)}" ${required?'required':''} ${type==='password'?'minlength="15" maxlength="256" autocomplete="new-password"':''}></div>`;}
function authPage(type){const modes={login:['Welcome back.','Sign in to view your orders.'],register:['Your account.','Create an account to place and track orders.'],recover:['Reset your password.','We’ll email a link if an eligible account matches.'],verifyrequest:['Verify your email.','Request a fresh email verification link.'],reset:['Choose a new password.','Use 15–256 characters.'],verify:['Verify your email.','Confirm your email to finish creating your account.']};const [title,description]=modes[type]||modes.login;return `<div class="auth-wrap"><p class="eyebrow">AERO AMINOS / ACCOUNT ACCESS</p><h1>${title}</h1><p>${description}</p><form id="auth-form" data-mode="${type}">${type==='register'?input('name','Name'):''}${['login','register','recover','verifyrequest'].includes(type)?input('email','Email address','email'):''}${['login','register','reset'].includes(type)?input('password','Password','password'):''}<div class="error-box" id="auth-error" role="alert"></div><button class="btn primary" type="submit">${({login:'Sign in',register:'Create account',recover:'Send reset link',verifyrequest:'Send verification link',reset:'Update password',verify:'Verify email'})[type]}</button></form><div class="auth-links">${type==='login'?'<a href="#/register">Create account</a><a href="#/recover">Forgot password?</a>':'<a href="#/login">Back to sign in</a>'}</div>${type==='login'?'<a class="small link" href="#/verifyrequest">Resend verification email</a>':''}</div>`;}
function checkoutPage(){if(!cart.length)return cartPage();return heading('ONE-TIME PURCHASE','Delivery & payment.','Review the final total before submitting payment.')+`<div class="cart-layout"><section class="panel"><div class="panel-head"><h2>Delivery address</h2></div><div class="panel-body"><form id="delivery-form"><div class="form-grid">${input('name','Recipient name','text',user.name)}${input('country','Country code (e.g. US)')}${input('line1','Street address')}${input('line2','Apartment / suite','text','',false)}${input('city','City')}${input('region','State / region')}${input('postal','Postal code')}</div><div class="error-box" id="checkout-error" role="alert"></div><button class="btn primary" type="submit">Review total</button></form></div></section><section class="panel"><div class="panel-head"><h2>Order summary</h2></div><div id="checkout-summary" class="panel-body"><p>Enter your address to calculate the final total.</p></div></section></div>`;}
function quoteSummary(){return `${quote.lines.map(l=>`<div class="order-line"><div>${escape(l.name)}<small>${escape(l.strength)} · Quantity ${l.quantity}</small></div><span>${money(l.price*l.quantity)}</span></div>`).join('')}<div class="totals"><div><span>Products</span><span>${money(quote.subtotal)}</span></div><div><span>Shipping</span><span>${money(quote.shipping)}</span></div><div><span>${quote.taxIncluded?'Tax included in prices':'Tax'}</span><span>${quote.taxIncluded?'Included':money(quote.tax)}</span></div><div><strong>Total ${escape(quote.currency)}</strong><strong>${money(quote.total)}</strong></div></div><p class="policy-note">Your order will be saved before payment. Fulfillment starts after payment is verified.</p><div class="payment-options">${settings.paypal?button('Pay with PayPal','pay-paypal','','primary'):''}${settings.zelle?button('Pay with Zelle','pay-zelle','','secondary'):''}</div><div id="payment-error" class="error-box" role="alert"></div>`;}
function orderTable(list){return list.length?`<div class="table-scroll"><table><caption class="sr-only">Orders</caption><thead><tr><th>Order</th>${user.role==='owner'?'<th>Customer</th>':''}<th>Payment</th><th>Fulfillment</th><th>Total</th></tr></thead><tbody>${list.map(o=>`<tr><td><button class="row-btn" data-action="order" data-id="${o.id}">${o.id.slice(0,13).toUpperCase()}</button><small>${date(o.created)}</small></td>${user.role==='owner'?`<td>${escape(o.name)}<small>${escape(o.email)}</small></td>`:''}<td>${badge(o.status)}<small>${o.method==='paypal'?'PayPal':'Zelle'}</small></td><td>${badge(o.fulfillment)}</td><td class="money">${money(o.total)}<small>${o.currency}</small></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><h3>No orders yet.</h3><p>Your orders will appear here.</p></div>';}
function overview(){if(user.role!=='owner')return heading('YOUR PERSONAL COLLECTION',`Welcome back, <em>${escape(user.name.split(' ')[0])}.</em>`,'Your orders, payment status and delivery details.')+`<section class="panel"><div class="panel-head"><h2>Recent orders</h2><a href="#/orders">View all</a></div>${orderTable(orders.slice(0,5))}</section>`;return heading('THE BUSINESS, AT A GLANCE','Welcome back.','One-time orders. Payment and fulfillment tracked separately.')+`<div class="stats"><div class="stat"><div class="stat-label">Paid product subtotal</div><div class="stat-value">${money(summary.paidSubtotal||0)}</div><div class="stat-foot">All time · Fully paid orders</div></div><div class="stat"><div class="stat-label">Ready to fulfill</div><div class="stat-value">${summary.ready||0}</div><div class="stat-foot">Paid · Unfulfilled</div></div><div class="stat"><div class="stat-label">Awaiting payment</div><div class="stat-value">${summary.pending||0}</div><div class="stat-foot">Payment not confirmed</div></div><div class="stat"><div class="stat-label">Total orders</div><div class="stat-value">${summary.orders||0}</div><div class="stat-foot">All time</div></div></div>${!summary.readiness?.ready?'<div class="notice"><p>Checkout is closed while store configuration is incomplete. <a class="link" href="#/setup">Review store setup</a></p></div>':''}<section class="panel"><div class="panel-head"><h2>Recent orders</h2><a href="#/orders">View all</a></div>${orderTable(orders.slice(0,7))}</section>`;}
function orderPage(){return heading('ORDER HISTORY','Every order. <em>In view.</em>','Open an order for payment, delivery and tracking details.')+`<section class="panel">${orderTable(orders)}<div class="pagination"><button class="btn sm" data-action="previous" ${page===0?'disabled':''}>Previous</button><span class="small muted">Page ${page+1}</span><button class="btn sm" data-action="next" ${!hasMore?'disabled':''}>Next</button></div></section>`;}
function inventory(){return heading('THE COLLECTION','Products & inventory.','Available stock excludes units reserved by pending orders.')+`<section class="panel"><div class="table-scroll"><table><caption class="sr-only">Inventory</caption><thead><tr><th>Product</th><th>One-time price</th><th>Available stock</th></tr></thead><tbody>${products.map(p=>`<tr><td>${escape(p.name)}<small>${p.strength}</small></td><td>${money(p.price)}</td><td><form class="stock-edit" data-inventory="${p.id}" data-version="${p.version}"><label class="sr-only" for="stock-${p.id}">${escape(p.name)} available stock</label><input id="stock-${p.id}" class="input" name="stock" type="number" min="0" max="100000" required value="${p.stock??''}" placeholder="Unconfirmed"><button class="btn sm" type="submit">Save</button></form></td></tr>`).join('')}</tbody></table></div></section>`;}
function setup(){return heading('STORE CONFIGURATION','Ready when you are.','Credentials are entered in the hosting provider’s protected settings.')+`<div class="account-grid"><section class="panel"><div class="panel-head"><h2>Checkout readiness</h2>${badge(summary.readiness?.ready?'Ready':'Pending')}</div><div class="panel-body"><ul class="setup-list">${(summary.readiness?.missing||[]).map(x=>`<li>${escape(x)}</li>`).join('')||'<li>Configuration checks passed. Provider testing and launch approval are still required.</li>'}</ul></div></section><section class="panel"><div class="panel-head"><h2>Order emails</h2></div><div class="panel-body">${summary.mail?.length?summary.mail.map(x=>`<div class="mini-row"><span>${escape(x.status)}</span><strong>${x.count}</strong></div>`).join(''):'<p>No email events yet.</p>'}<p class="policy-note">Accepted means the mail provider accepted a message; it does not confirm inbox delivery.</p></div></section></div>`;}
function activity(){return heading('BUSINESS ACTIVITY','Every change, recorded.','Payment confirmations, inventory changes and fulfillment updates.')+`<section class="panel">${summary.activity?.length?summary.activity.map(e=>`<div class="inline-alert"><div><div class="alert-kind">${escape(e.event.replaceAll('_',' ').toUpperCase())}</div><p class="order-title">${escape(e.order_id||e.detail)}</p></div><span class="event-time">${date(e.created)}</span></div>`).join(''):'<div class="empty">No activity recorded yet.</div>'}</section>`;}
function account(){return heading('YOUR ACCOUNT','Account details.','Manage your access and view your orders.')+`<section class="panel"><div class="panel-body"><dl class="detail-grid" style="border:0;padding:0;margin:0"><div><dt>Name</dt><dd>${escape(user.name)}</dd></div><div><dt>Email</dt><dd>${escape(user.email)}</dd></div></dl><div class="order-actions"><a class="btn" href="#/recover">Reset password</a>${button('Sign out','logout','','secondary')}</div></div></section>`;}
async function render(){const r=routeName();if(['overview','orders','account','inventory','activity','setup','checkout'].includes(r)&&!user){location.hash='/login';return;}
 try{if(['overview','orders','activity','setup'].includes(r)&&user){const result=await api('/orders?page='+page);orders=result.orders;hasMore=result.hasMore;if(user.role==='owner')summary=await api('/owner/summary');}
 if(['inventory','activity','setup'].includes(r)&&user?.role!=='owner'){location.hash='/overview';return;}
 const content=({shop,cart:cartPage,checkout:checkoutPage,overview,orders:orderPage,inventory,activity,setup,account})[r];app.innerHTML=shell(content?content():authPage(['login','register','recover','reset','verify','verifyrequest'].includes(r)?r:'login'),['overview','orders','inventory','activity','setup','account'].includes(r));document.title=`${r==='shop'?'Product Collection':r.charAt(0).toUpperCase()+r.slice(1)} — Aero Aminos`;
 }catch(error){app.innerHTML=shell(`<div class="error-state"><h1>We couldn’t load this page.</h1><p>${escape(error.message)}</p>${button('Try again','reload','','primary')}</div>`);}
}
function openModal(title,body,actions=''){document.querySelector('#modal-content').innerHTML=`<div class="modal-header"><h2 id="modal-title">${title}</h2><button class="icon-btn" data-action="close" aria-label="Close dialog">×</button></div><div class="modal-body">${body}</div>${actions?`<div class="modal-footer">${actions}</div>`:''}`;if(!modal.open)modal.showModal();else modal.querySelector('[data-action="close"]').focus();}
async function openOrder(id){const result=await api('/orders/'+encodeURIComponent(id));currentOrder=result.order;const o=currentOrder,a=o.address;openModal('Order details',`<p class="order-title">${o.id}</p><div style="display:flex;gap:8px;flex-wrap:wrap">${badge(o.status)}${badge(o.fulfillment)}</div>${o.lines.map(l=>`<div class="order-line"><div>${escape(l.name)}<small>${escape(l.strength)} · Quantity ${l.quantity}</small></div><span>${money(l.price*l.quantity)}</span></div>`).join('')}<div class="totals"><div><span>Products</span><span>${money(o.subtotal)}</span></div><div><span>Shipping</span><span>${money(o.shipping)}</span></div><div><span>Additional tax</span><span>${money(o.tax)}</span></div><div><strong>Total ${o.currency}</strong><strong>${money(o.total)}</strong></div></div><h3 style="margin-top:25px">Delivery</h3><address class="address">${[a.name,a.line1,a.line2,`${a.city}, ${a.region} ${a.postal}`,a.country].filter(Boolean).map(escape).join('<br>')}</address>${o.tracking_number?`<p>Carrier: ${escape(o.tracking_carrier)}<br>Tracking: ${escape(o.tracking_number)}</p>`:''}${result.instructions?`<div class="notice neutral" style="margin-top:20px"><p>Send ${money(o.total)} to <strong>${escape(result.instructions.name)}</strong> at <strong>${escape(result.instructions.recipient)}</strong> using Zelle. Include <strong>${o.id}</strong> in the memo. Your order stays unpaid until receipt is verified.</p></div>`:''}<div id="paypal-buttons" style="margin-top:24px"></div>`,(user.role==='owner'?`${o.method==='zelle'&&o.status==='Awaiting payment'?button('Confirm Zelle receipt','confirm-zelle',o.id,'primary')+button('Cancel unpaid order','cancel-zelle',o.id,'danger'):''}${o.status==='Paid'&&o.fulfillment==='Unfulfilled'?button('Record shipment','ship',o.id,'primary'):''}`:'')+button('Close','close','','secondary'));
 if(o.method==='paypal'&&['Awaiting payment','Pending'].includes(o.status)&&settings.paypal)await mountPaypal(o.id);
}
let paypalReady;
async function mountPaypal(id){const container=document.querySelector('#paypal-buttons');if(!container)return;
 try{if(!window.paypal){if(!paypalReady)paypalReady=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://www.paypal.com/sdk/js?'+new URLSearchParams({'client-id':settings.paypalClient,currency:settings.currency,intent:'capture',components:'buttons'});script.onload=resolve;script.onerror=()=>{paypalReady=null;script.remove();reject(new Error('PayPal could not load. Reopen this order to retry.'));};document.head.append(script);});await paypalReady;}
  await window.paypal.Buttons({style:{layout:'vertical',color:'gold',shape:'rect',label:'pay'},createOrder:async()=>{const result=await api('/orders/'+id+'/paypal',{method:'POST',body:{}});return result.id;},onApprove:async()=>{try{const result=await api('/orders/'+id+'/capture',{method:'POST',body:{}});await openOrder(id);toast(result.order.status==='Paid'?'Payment received. Your order is saved.':'Payment is pending. We will confirm its status.');await refreshOrdersBehindModal();}catch(error){toast(error.message);}},onCancel:()=>toast('PayPal was closed. Your order remains unpaid.'),onError:()=>toast('PayPal could not complete payment. Check this order before trying again.')}).render(container);
 }catch(error){container.innerHTML=`<p class="error-box">${escape(error.message)}</p>`;}
}
async function refreshOrdersBehindModal(){if(['orders','overview'].includes(routeName()))await render();}
function saveCart(){localStorage.setItem('aero-cart',JSON.stringify(cart));quote=null;checkoutInput=null;}
async function choosePayment(method){if(!quote||!checkoutInput)throw new Error('Review your delivery details first.');const key=checkoutInput.key;const data=await api('/orders',{method:'POST',headers:{'Idempotency-Key':key},body:{items:checkoutInput.items,address:checkoutInput.address,method}});cart=[];saveCart();location.hash='/orders';await render();await openOrder(data.order.id);}
document.addEventListener('input',e=>{if(e.target.id==='product-search'){search=e.target.value;document.querySelector('#product-results').innerHTML=productCards(products.filter(p=>`${p.name} ${p.strength}`.toLowerCase().includes(search.toLowerCase())));}if(e.target.closest('#delivery-form')){quote=null;checkoutInput=null;document.querySelector('#checkout-summary').innerHTML='<p>Review the total again after changing delivery details.</p>';}});
document.addEventListener('change',e=>{if(e.target.dataset.quantity){const q=Number(e.target.value);if(!Number.isInteger(q)||q<1||q>99){toast('Choose a whole quantity between 1 and 99.');return;}const l=cart.find(x=>x.id===e.target.dataset.quantity);if(l)l.quantity=q;saveCart();render();}});
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const {action,id}=el.dataset;if(busy&&action!=='close')return;try{
 if(action==='close'){modal.close();return;}if(action==='add'){const p=item(id),l=cart.find(x=>x.id===id);if(l&&l.quantity>=Math.min(99,p.stock??99))throw new Error('No more available units can be added.');if(l)l.quantity++;else cart.push({id,quantity:1});saveCart();await render();toast(p.name+' added to your bag.');return;}
 if(action==='remove'){cart=cart.filter(x=>x.id!==id);saveCart();await render();return;}
 busy=true;el.disabled=true;
 if(action==='logout'){await api('/auth/logout',{method:'POST',body:{}});await refreshSession();location.hash='/login';await render();}
 if(action==='reload')await init();
 if(action==='previous'||action==='next'){page+=action==='next'?1:-1;await render();}
 if(action==='order')await openOrder(id);
 if(action==='pay-paypal'||action==='pay-zelle')await choosePayment(action==='pay-paypal'?'paypal':'zelle');
 if(action==='confirm-zelle')openModal('Verify received payment.',`<p>Confirm the full <strong>${money(currentOrder.total)} ${currentOrder.currency}</strong> is visible in the business bank account. A customer screenshot is not payment confirmation.</p><form id="zelle-form" data-id="${id}">${input('reference','Bank transaction reference')}${input('password','Your owner password','password')}<label class="checkbox-label"><input type="checkbox" name="confirmed" required>I verified receipt of the full order amount in the business account.</label><div class="error-box" role="alert"></div><button class="btn primary full" type="submit">Confirm received payment</button></form>`);
 if(action==='cancel-zelle')openModal('Cancel unpaid order?',`<p>This cancels the unpaid Zelle order and returns its reserved units to available stock. Verify that no payment has arrived first.</p>`,button('Keep order','close','','secondary')+button('Cancel unpaid order','do-cancel-zelle',id,'danger'));
 if(action==='do-cancel-zelle'){await api('/owner/orders/'+id+'/cancel-zelle',{method:'POST',body:{}});await openOrder(id);await refreshOrdersBehindModal();toast('Unpaid order canceled. Stock released.');}
 if(action==='ship')openModal('Record shipment.',`<form id="ship-form" data-id="${id}">${input('carrier','Carrier')}${input('tracking','Tracking number')}<div class="error-box" role="alert"></div><button class="btn primary full" type="submit">Mark shipped</button></form>`);
 }catch(error){toast(error.message);}finally{busy=false;if(el.isConnected)el.disabled=false;}});
document.addEventListener('submit',async e=>{const form=e.target;if(!['auth-form','delivery-form','zelle-form','ship-form'].includes(form.id)&&!form.dataset.inventory)return;e.preventDefault();if(busy)return;busy=true;const submit=form.querySelector('[type="submit"]');submit.disabled=true;const values=Object.fromEntries(new FormData(form));try{
 if(form.id==='auth-form'){const mode=form.dataset.mode,token=new URLSearchParams(location.hash.split('?')[1]||'').get('token');let path=({login:'login',register:'register',recover:'reset-request',verifyrequest:'verify-request',reset:'reset',verify:'verify'})[mode];const result=await api('/auth/'+path,{method:'POST',body:{...values,...(token?{token}:{})}});if(mode==='login'){user=result.user;csrf=result.csrf;location.hash=cart.length?'/cart':'/overview';await render();}else if(['reset','verify'].includes(mode)){history.replaceState(null,'','#/login');await refreshSession();await render();toast(result.message);}else{form.innerHTML=`<div class="notice neutral"><p>${escape(result.message)}</p></div>`;}}
 if(form.id==='delivery-form'){quote=await api('/quote',{method:'POST',body:{items:cart,address:values}});checkoutInput={items:structuredClone(cart),address:values,key:crypto.randomUUID()};document.querySelector('#checkout-summary').innerHTML=quoteSummary();}
 if(form.id==='zelle-form'){await api('/owner/orders/'+form.dataset.id+'/confirm-zelle',{method:'POST',body:{reference:values.reference,password:values.password,confirmed:values.confirmed==='on',amount:currentOrder.total}});await openOrder(form.dataset.id);await refreshOrdersBehindModal();toast('Payment confirmed and recorded.');}
 if(form.id==='ship-form'){await api('/owner/orders/'+form.dataset.id+'/ship',{method:'POST',body:values});await openOrder(form.dataset.id);await refreshOrdersBehindModal();toast('Shipment recorded. Customer notification queued.');}
 if(form.dataset.inventory){await api('/owner/inventory/'+form.dataset.inventory,{method:'POST',body:{stock:Number(values.stock),version:Number(form.dataset.version)}});const data=await api('/catalog');products=data.products;await render();toast('Available inventory updated.');}
 }catch(error){const target=form.querySelector('.error-box');if(target)target.textContent=error.message;else toast(error.message);}finally{busy=false;if(submit.isConnected)submit.disabled=false;}});
window.addEventListener('hashchange',()=>{page=0;render();window.scrollTo(0,0);});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
async function init(){try{await refreshSession();const data=await api('/catalog');products=data.products;settings=data;await render();}catch{app.innerHTML=`<div class="error-state"><img class="brand" src="/logo.png" alt="Aero Aminos"><h1>The store is temporarily unavailable.</h1><p>Please try again shortly.</p>${button('Try again','reload','','primary')}</div>`;}}
init();
