import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createApp} from '../server/app.js';
import {configuration,readiness} from '../server/config.js';
import {openDatabase} from '../server/db.js';
import {hashPassword,digest} from '../server/security.js';
import {paypalClient} from '../server/paypal.js';

const origin='http://localhost:4173',password='Aero Test Password 2026!';
async function fixture(overrides={}){
 const dir=mkdtempSync(join(tmpdir(),'aero-test-'));const config={...configuration({}),origin,dbPath:join(dir,'store.sqlite'),checkoutEnabled:true,policyApproved:true,catalogApproved:true,currency:'USD',shipping:700,taxMode:'exclusive',taxRate:825,taxShipping:false,countries:['US'],ownerEmail:'owner@example.com',supportEmail:'support@example.com',paypalClient:'test-client',paypalSecret:'test-secret',paypalMerchant:'TESTMERCHANT',paypalWebhook:'TESTWEBHOOK',zelleRecipient:'payments@example.com',zelleName:'Aero Test',zelleApproved:true,mailEnabled:true,mailHost:'test.invalid',mailFrom:'test@example.com',...overrides};
 const db=openDatabase(config.dbPath),ids={owner:randomUUID(),a:randomUUID(),b:randomUUID()},hash=await hashPassword(password);
 for(const [key,id]of Object.entries(ids))db.prepare('INSERT INTO users(id,email,name,password,role,verified,created) VALUES(?,?,?,?,?,1,?)').run(id,key+'@example.com',key==='owner'?'Owner':key==='a'?'Customer A':'Customer B',hash,key==='owner'?'owner':'customer',Date.now());
 db.prepare('UPDATE products SET stock=10').run();let creates=0,captures=0;const provider=new Map();
 const paypal={async create(o){creates++;const id='PP'+creates;provider.set(id,{id,status:'APPROVED',purchase_units:[{custom_id:o.id,payee:{merchant_id:config.paypalMerchant},amount:{currency_code:o.currency,value:(o.total/100).toFixed(2)}}]});return {id};},async get(id){return structuredClone(provider.get(id));},async capture(id){captures++;const p=provider.get(id);p.status='COMPLETED';p.purchase_units[0].payments={captures:[{id:'CAPTURE'+id,status:'COMPLETED',amount:{...p.purchase_units[0].amount}}]};return structuredClone(p);},async verify(headers){return headers['paypal-transmission-sig']==='VALID';}};
 const sent=[];const transport={async sendMail(message){sent.push(message);return {accepted:[message.to],rejected:[]};}};
 const api=createApp({config,db,paypal,transport});const server=await new Promise(resolve=>{const s=api.app.listen(0,'127.0.0.1',()=>resolve(s));});const base='http://127.0.0.1:'+server.address().port;
 const client=()=>{let cookie='',csrf='';return {async request(path,body,extra={}){const response=await fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:config.origin,Cookie:cookie,'X-CSRF-Token':csrf,'Content-Type':'application/json',...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];const data=await response.json();if(data.csrf)csrf=data.csrf;return {status:response.status,data,headers:response.headers};},async login(key){await this.request('/me');const r=await this.request('/auth/login',{email:key+'@example.com',password});assert.equal(r.status,200);return this;}};};
 const a=await client().login('a'),b=await client().login('b'),owner=await client().login('owner');
 const address={name:'Test Buyer',line1:'123 Test Street',line2:'',city:'Test City',region:'TX',postal:'00000',country:'US'};
 const body=(method='zelle')=>({items:[{id:'AA-004',quantity:2},{id:'AA-010',quantity:1}],address,method,total:1});
 return {api,db,config,ids,provider,paypal,sent,client,a,b,owner,body,address,get creates(){return creates;},get captures(){return captures;},async close(){await new Promise(resolve=>server.close(resolve));db.close();rmSync(dir,{recursive:true,force:true});}};
}

test('Catalog exact one-time prices; subscriptions absent; unconfigured production checkout closed',async()=>{const f=await fixture({checkoutEnabled:false});try{const r=await f.a.request('/catalog');assert.equal(r.data.products.length,21);assert.deepEqual(r.data.products.map(p=>p.price),[5900,3200,3500,1500,3500,2000,7900,3400,2500,3000,2400,1700,3400,2600,2500,2000,2000,1400,3000,1500,2100]);assert.equal(r.data.products[9].name,'NAD+');assert.equal(r.data.checkoutReady,false);assert.equal((await f.a.request('/orders',f.body(),{'Idempotency-Key':randomUUID()})).status,503);assert.equal((await f.a.request('/subscriptions')).status,404);}finally{await f.close();}});

test('Authentication, CSRF, ownership and owner permission boundaries',async()=>{const f=await fixture();try{const anon=f.client();await anon.request('/me');assert.equal((await anon.request('/orders')).status,401);assert.equal((await f.a.request('/owner/summary')).status,403);assert.equal((await f.a.request('/quote',f.body(),{Origin:'https://evil.example'})).status,403);assert.equal((await f.a.request('/quote',f.body(),{'X-CSRF-Token':'invalid'})).status,403);const r=await f.a.request('/orders',f.body(),{'Idempotency-Key':randomUUID()});assert.equal(r.status,201);assert.equal((await f.b.request('/orders/'+r.data.order.id)).status,404);assert.equal((await f.b.request('/orders')).data.orders.length,0);assert.equal((await f.a.request('/owner/orders/'+r.data.order.id+'/confirm-zelle',{})).status,403);assert.equal((await f.owner.request('/orders')).data.orders.length,1);assert.ok(r.headers.get('cache-control').includes('no-store'));}finally{await f.close();}});

test('Server calculates totals; idempotency prevents duplicate stock reservations and mismatched key reuse',async()=>{const f=await fixture();try{const key=randomUUID(),r=await f.a.request('/orders',f.body(),{'Idempotency-Key':key});assert.equal(r.status,201);assert.equal(r.data.order.subtotal,6000);assert.equal(r.data.order.shipping,700);assert.equal(r.data.order.tax,495);assert.equal(r.data.order.total,7195);assert.equal(r.data.order.status,'Awaiting payment');const again=await f.a.request('/orders',f.body(),{'Idempotency-Key':key});assert.equal(again.data.order.id,r.data.order.id);assert.equal(f.db.prepare("SELECT stock FROM products WHERE id='AA-004'").get().stock,8);const other=f.body();other.items[0].quantity=3;assert.equal((await f.a.request('/orders',other,{'Idempotency-Key':key})).status,409);assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM orders').get().n,1);}finally{await f.close();}});

test('Missing/insufficient stock, malformed quantities, duplicate items and unsupported destinations are rejected',async()=>{const f=await fixture();try{for(const quantity of [-1,0,1.5,100]){const body=f.body();body.items[0].quantity=quantity;assert.equal((await f.a.request('/quote',body)).status,400);}const body=f.body();body.items.push(body.items[0]);assert.equal((await f.a.request('/quote',body)).status,400);body.items=f.body().items;body.address={...f.address,country:'CA'};assert.equal((await f.a.request('/quote',body)).status,400);f.db.prepare("UPDATE products SET stock=NULL WHERE id='AA-004'").run();assert.equal((await f.a.request('/quote',f.body())).status,409);assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM orders').get().n,0);}finally{await f.close();}});

test('Concurrent last-unit orders cannot oversell',async()=>{const f=await fixture();try{f.db.prepare("UPDATE products SET stock=1 WHERE id='AA-004'").run();const body={items:[{id:'AA-004',quantity:1}],address:f.address,method:'zelle'};const results=await Promise.all([f.a.request('/orders',body,{'Idempotency-Key':randomUUID()}),f.b.request('/orders',body,{'Idempotency-Key':randomUUID()})]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);assert.equal(f.db.prepare("SELECT stock FROM products WHERE id='AA-004'").get().stock,0);}finally{await f.close();}});

test('Zelle requires owner password, amount and reference; paid-only fulfillment; durable notification outbox',async()=>{const f=await fixture();try{const o=(await f.a.request('/orders',f.body(),{'Idempotency-Key':randomUUID()})).data.order;assert.equal((await f.owner.request('/owner/orders/'+o.id+'/ship',{carrier:'Test Carrier',tracking:'TRACK123'})).status,409);const path='/owner/orders/'+o.id+'/confirm-zelle';assert.equal((await f.owner.request(path,{confirmed:true,amount:o.total,reference:'BANK1',password:'wrong'})).status,403);assert.equal((await f.owner.request(path,{confirmed:true,amount:1,reference:'BANK1',password})).status,400);assert.equal((await f.owner.request(path,{confirmed:true,amount:o.total,reference:'BANK1',password})).status,200);assert.equal((await f.a.request('/orders/'+o.id)).data.order.status,'Paid');assert.equal((await f.owner.request(path,{confirmed:true,amount:o.total,reference:'BANK1',password})).status,409);assert.equal((await f.owner.request('/owner/orders/'+o.id+'/ship',{carrier:'Test Carrier',tracking:'TRACK123'})).status,200);const detail=(await f.a.request('/orders/'+o.id)).data.order;assert.equal(detail.fulfillment,'Shipped');assert.equal(detail.tracking_number,'TRACK123');await f.api.flushMail();assert.equal(f.sent.length,4);await f.api.flushMail();assert.equal(f.sent.length,4);assert.equal(f.db.prepare("SELECT COUNT(*) AS n FROM outbox WHERE status='accepted' AND body='' ").get().n,4);}finally{await f.close();}});

test('Canceling unpaid Zelle releases reserved stock once and inventory uses optimistic version checking',async()=>{const f=await fixture();try{const o=(await f.a.request('/orders',f.body(),{'Idempotency-Key':randomUUID()})).data.order;assert.equal((await f.owner.request('/owner/orders/'+o.id+'/cancel-zelle',{})).status,200);assert.equal(f.db.prepare("SELECT stock FROM products WHERE id='AA-004'").get().stock,10);assert.equal((await f.owner.request('/owner/orders/'+o.id+'/cancel-zelle',{})).status,409);const p=f.db.prepare("SELECT * FROM products WHERE id='AA-004'").get();assert.equal((await f.owner.request('/owner/inventory/'+p.id,{stock:20,version:p.version})).status,200);assert.equal((await f.owner.request('/owner/inventory/'+p.id,{stock:99,version:p.version})).status,409);}finally{await f.close();}});

test('PayPal create/capture idempotency and amount/merchant binding',async()=>{const f=await fixture();try{const o=(await f.a.request('/orders',f.body('paypal'),{'Idempotency-Key':randomUUID()})).data.order;const created=await f.a.request('/orders/'+o.id+'/paypal',{});assert.equal(created.status,200);await f.a.request('/orders/'+o.id+'/paypal',{});assert.equal(f.creates,1);const p=f.provider.get(created.data.id);p.purchase_units[0].payee.merchant_id='WRONG';assert.equal((await f.a.request('/orders/'+o.id+'/capture',{})).status,409);assert.equal((await f.a.request('/orders/'+o.id)).data.order.status,'Awaiting payment');assert.equal(f.captures,0);p.purchase_units[0].payee.merchant_id='TESTMERCHANT';assert.equal((await f.a.request('/orders/'+o.id+'/capture',{})).data.order.status,'Paid');await f.a.request('/orders/'+o.id+'/capture',{});assert.equal(f.captures,1);assert.equal(f.db.prepare("SELECT COUNT(*) AS n FROM audit WHERE event='payment_confirmed'").get().n,1);}finally{await f.close();}});

test('PayPal pending is not paid; capture retries reconcile an uncertain result',async()=>{const f=await fixture();try{const o=(await f.a.request('/orders',f.body('paypal'),{'Idempotency-Key':randomUUID()})).data.order;const created=await f.a.request('/orders/'+o.id+'/paypal',{});const capture=f.paypal.capture;f.paypal.capture=async id=>{await capture(id);throw new Error('Network dropped after capture');};assert.equal((await f.a.request('/orders/'+o.id+'/capture',{})).status,500);assert.equal((await f.a.request('/orders/'+o.id)).data.order.status,'Awaiting payment');f.provider.get(created.data.id).purchase_units[0].payments.captures[0].status='PENDING';assert.equal((await f.a.request('/orders/'+o.id+'/capture',{})).data.order.status,'Pending');f.provider.get(created.data.id).purchase_units[0].payments.captures[0].status='COMPLETED';assert.equal((await f.a.request('/orders/'+o.id+'/capture',{})).data.order.status,'Paid');assert.equal(f.captures,1);}finally{await f.close();}});

test('Signed webhook reconciliation, replay deduplication, refunds and no paid-state regression',async()=>{const f=await fixture();try{const o=(await f.a.request('/orders',f.body('paypal'),{'Idempotency-Key':randomUUID()})).data.order;const created=(await f.a.request('/orders/'+o.id+'/paypal',{})).data;await f.paypal.capture(created.id);const event={id:'EV1',event_type:'PAYMENT.CAPTURE.COMPLETED',resource:{supplementary_data:{related_ids:{order_id:created.id}}}};assert.equal((await f.a.request('/paypal/webhook',event)).status,401);assert.equal((await f.a.request('/paypal/webhook',event,{'paypal-transmission-sig':'VALID'})).status,200);await f.a.request('/paypal/webhook',event,{'paypal-transmission-sig':'VALID'});assert.equal(f.db.prepare('SELECT COUNT(*) AS n FROM webhooks').get().n,1);const refund={id:'EV2',event_type:'PAYMENT.CAPTURE.REFUNDED',resource:{id:'REF1',amount:{currency_code:'USD',value:(o.total/100).toFixed(2)},supplementary_data:{related_ids:{capture_id:'CAPTURE'+created.id}}}};await f.a.request('/paypal/webhook',refund,{'paypal-transmission-sig':'VALID'});assert.equal((await f.a.request('/orders/'+o.id)).data.order.status,'Refunded');await f.a.request('/paypal/webhook',{...event,id:'EV3'},{'paypal-transmission-sig':'VALID'});assert.equal((await f.a.request('/orders/'+o.id)).data.order.status,'Refunded');assert.equal((await f.owner.request('/owner/orders/'+o.id+'/ship',{carrier:'X',tracking:'Y'})).status,409);}finally{await f.close();}});

test('Email verification, non-enumerating recovery, single-use reset, expiry and session invalidation',async()=>{const f=await fixture();try{const visitor=f.client();await visitor.request('/me');let result=await visitor.request('/auth/register',{email:'new@example.com',name:'New Customer',password});assert.equal(result.status,202);assert.equal((await visitor.request('/auth/login',{email:'new@example.com',password})).status,403);let mail=f.db.prepare("SELECT body FROM outbox WHERE recipient='new@example.com'").get();const verifyToken=mail.body.match(/token=([A-Za-z0-9_-]+)/)[1];assert.equal((await visitor.request('/auth/verify',{token:verifyToken})).status,200);assert.equal((await visitor.request('/auth/verify',{token:verifyToken})).status,400);assert.equal((await visitor.request('/auth/login',{email:'new@example.com',password})).status,200);const known=await visitor.request('/auth/reset-request',{email:'new@example.com'}),unknown=await visitor.request('/auth/reset-request',{email:'none@example.com'});assert.deepEqual(known.data,unknown.data);mail=f.db.prepare("SELECT body FROM outbox WHERE recipient='new@example.com' AND subject LIKE 'Reset%'").get();const resetToken=mail.body.match(/token=([A-Za-z0-9_-]+)/)[1];result=await visitor.request('/auth/reset',{token:resetToken,password:'Different Password 2026!'});assert.equal(result.status,200);assert.equal((await visitor.request('/orders')).status,401);await visitor.request('/me');assert.equal((await visitor.request('/auth/reset',{token:resetToken,password:'Different Password 2026!'})).status,400);assert.equal((await visitor.request('/auth/login',{email:'new@example.com',password:'Different Password 2026!'})).status,200);await visitor.request('/auth/reset-request',{email:'new@example.com'});mail=f.db.prepare("SELECT body FROM outbox WHERE recipient='new@example.com' AND subject LIKE 'Reset%' ORDER BY created DESC LIMIT 1").get();const expired=mail.body.match(/token=([A-Za-z0-9_-]+)/)[1];f.db.prepare('UPDATE tokens SET expires=0 WHERE hash=?').run(digest(expired));assert.equal((await visitor.request('/auth/reset',{token:expired,password})).status,400);}finally{await f.close();}});

test('Orders and sessions persist across app instances; production cookie flags and secret redaction',async()=>{const f=await fixture({production:true,origin:'https://store.example'});try{const visitor=f.client();const session=await visitor.request('/me');const cookie=session.headers.get('set-cookie');assert.match(cookie,/__Host-aero/);assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);assert.match(cookie,/SameSite=Lax/);const response=await f.a.request('/catalog');assert.ok(!JSON.stringify(response.data).includes('test-secret'));const copy=openDatabase(f.config.dbPath);assert.equal(copy.prepare('SELECT COUNT(*) AS n FROM users').get().n,3);assert.ok(copy.prepare('SELECT COUNT(*) AS n FROM sessions').get().n>0);copy.close();}finally{await f.close();}});

test('Real PayPal adapter sends correct server amounts, stable request IDs and verifies webhook signatures',async()=>{const requests=[];const c={...configuration({}),paypalClient:'CLIENT',paypalSecret:'SECRET',paypalMerchant:'MERCHANT',paypalWebhook:'WEBHOOK',origin};const adapter=paypalClient(c,async(url,init)=>{requests.push({url,init});return {ok:true,status:200,json:async()=>url.endsWith('/token')?{access_token:'ACCESS',expires_in:3600}:url.includes('verify-webhook-signature')?{verification_status:'SUCCESS'}:{id:'PP123'}};});const order={id:'AERO-TEST',currency:'USD',total:1234,address:JSON.stringify({name:'Test',line1:'Test',city:'City',region:'TX',postal:'00000',country:'US'})};await adapter.create(order);await adapter.capture('PP123');const headers=Object.fromEntries(['paypal-auth-algo','paypal-cert-url','paypal-transmission-id','paypal-transmission-sig','paypal-transmission-time'].map(x=>[x,'test']));assert.equal(await adapter.verify(headers,{id:'EV'}),true);assert.equal(await adapter.verify({},{}),false);const create=requests.find(x=>x.url.endsWith('/v2/checkout/orders'));assert.equal(JSON.parse(create.init.body).purchase_units[0].amount.value,'12.34');assert.equal(create.init.headers['PayPal-Request-Id'],'create-AERO-TEST');assert.ok(requests.every(x=>x.url.startsWith('https://api-m.sandbox.paypal.com/')));});
