import express from 'express';
import helmet from 'helmet';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {openDatabase,transaction,audit} from './db.js';
import {configuration,readiness} from './config.js';
import {token,digest,hashPassword,checkPassword,validatePassword,fail,limited,emailValue,field} from './security.js';
import {paypalClient} from './paypal.js';
import {queue,mailWorker} from './mail.js';

export function createApp({config=configuration(),db=openDatabase(config.dbPath),paypal=paypalClient(config),transport}={}){
 const app=express(), production=config.production, cookieName=production?'__Host-aero':'aero';
 const dummyPassword=hashPassword(token());const locks=new Map();
 app.disable('x-powered-by');if(config.trustedProxyHops)app.set('trust proxy',config.trustedProxyHops);
 app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'",'https://www.paypal.com','https://www.sandbox.paypal.com','https://www.paypalobjects.com'],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:','https://*.paypal.com','https://*.paypalobjects.com'],connectSrc:["'self'",'https://*.paypal.com','https://*.paypalobjects.com'],frameSrc:['https://*.paypal.com'],formAction:["'self'"],upgradeInsecureRequests:production?[]:null}},crossOriginOpenerPolicy:{policy:'same-origin-allow-popups'}}));
 app.use('/api',(_req,res,next)=>{res.set('Cache-Control','no-store');next();});
 app.use(express.json({limit:'32kb'}));
 app.use('/api',(req,res,next)=>{
  if(req.path==='/paypal/webhook'||req.path==='/health')return next();
  const value=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.slice(cookieName.length+1);
  let session=value&&db.prepare('SELECT s.*,u.email,u.name,u.role,u.verified FROM sessions s LEFT JOIN users u ON u.id=s.user_id WHERE s.hash=? AND s.expires>?').get(digest(value),Date.now());
  if(!session){limited(db,'session:'+digest(req.ip||'unknown'),120,900);const raw=token();session={hash:digest(raw),user_id:null,csrf:token(),expires:Date.now()+8*3600000};db.prepare('INSERT INTO sessions(hash,user_id,csrf,expires) VALUES(?,?,?,?)').run(session.hash,null,session.csrf,session.expires);res.cookie(cookieName,raw,{httpOnly:true,secure:production,sameSite:'lax',path:'/',maxAge:8*3600000});}
  req.session=session;
  if(!['GET','HEAD','OPTIONS'].includes(req.method)){
   if(req.headers.origin!==config.origin||req.get('X-CSRF-Token')!==session.csrf)return next(Object.assign(new Error('Request could not be verified. Refresh and try again.'),{status:403}));
  }
  next();
 });
 const auth=(req,_res,next)=>{if(!req.session?.user_id)return next(Object.assign(new Error('Please sign in.'),{status:401}));next();};
 const owner=(req,res,next)=>auth(req,res,()=>{if(req.session.role!=='owner')return next(Object.assign(new Error('Owner access required.'),{status:403}));next();});
 const cleanUser=s=>s?.user_id?{id:s.user_id,name:s.name,email:s.email,role:s.role,verified:!!s.verified}:null;
 const publicOrder=o=>({...o,lines:JSON.parse(o.lines),address:JSON.parse(o.address),request_key:undefined,fingerprint:undefined});
 const orderFor=(req,id)=>{const o=db.prepare('SELECT * FROM orders WHERE id=?').get(id);if(!o||(req.session.role!=='owner'&&o.user_id!==req.session.user_id))fail(404,'Order not found.');return o;};
 const csrfSession=(req,res,user)=>{db.prepare('DELETE FROM sessions WHERE hash=?').run(req.session.hash);const raw=token(),csrf=token();db.prepare('INSERT INTO sessions(hash,user_id,csrf,expires) VALUES(?,?,?,?)').run(digest(raw),user.id,csrf,Date.now()+8*3600000);res.cookie(cookieName,raw,{httpOnly:true,secure:production,sameSite:'lax',path:'/',maxAge:8*3600000});return csrf;};
 const authLimit=(req,key,max=8)=>{limited(db,`${key}:ip:${digest(req.ip||'unknown')}`,max*3,900);limited(db,`${key}:email:${digest(String(req.body.email||'').trim().toLowerCase())}`,max,900);};
 const mailReady=()=>{if(!config.mailEnabled||!config.mailHost||!config.mailFrom)fail(503,'Account emails are not available yet. Please try again later.');};
 const sendToken=(user,kind)=>{const raw=token(),expires=Date.now()+30*60000;db.prepare('DELETE FROM tokens WHERE user_id=? AND kind=?').run(user.id,kind);db.prepare('INSERT INTO tokens(hash,user_id,kind,expires) VALUES(?,?,?,?)').run(digest(raw),user.id,kind,expires);queue(db,raw,user.email,kind==='verify'?'Verify your Aero Aminos email':'Reset your Aero Aminos password',`Hello ${user.name},\n\n${kind==='verify'?'Verify your email':'Set a new password'} using this link:\n${config.origin}/#/${kind}?token=${raw}\n\nThis link expires in 30 minutes and can be used once. If you did not request it, ignore this email.\n\nAero Aminos`,expires);};
 app.get('/api/health',(_req,res)=>{db.prepare('SELECT 1').get();res.json({ok:true});});
 app.get('/api/me',(req,res)=>res.json({user:cleanUser(req.session),csrf:req.session.csrf}));
 app.get('/api/catalog',(_req,res)=>res.json({products:db.prepare('SELECT id,name,strength,price,stock,version FROM products ORDER BY id').all(),currency:config.currency,checkoutReady:readiness(config).ready,paypal:readiness(config).paypal,paypalClient:readiness(config).paypal?config.paypalClient:null,paypalMode:config.paypalMode,zelle:readiness(config).zelle,supportEmail:config.supportEmail}));
 app.post('/api/auth/register',async(req,res)=>{mailReady();authLimit(req,'register',4);const email=emailValue(req.body.email),name=field(req.body.name,'name',100),password=req.body.password;if(!email||!validatePassword(password))fail(400,'Enter a valid email and a password of 15–256 characters.');const hash=await hashPassword(password);const existing=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!existing){const user={id:randomUUID(),email,name};transaction(db,()=>{db.prepare("INSERT INTO users(id,email,name,password,role,created) VALUES(?,?,?,?,'customer',?)").run(user.id,email,name,hash,Date.now());sendToken(user,'verify');});}res.status(202).json({message:'If this email can be registered, a verification link will arrive shortly. If you already have an account, sign in or reset your password.'});});
 app.post('/api/auth/login',async(req,res)=>{authLimit(req,'login');const user=db.prepare('SELECT * FROM users WHERE email=?').get(emailValue(req.body.email)||'');const valid=await checkPassword(req.body.password,user?.password||await dummyPassword);if(!user||!valid)fail(401,'Email or password did not match.');if(!user.verified)fail(403,'Verify your email before signing in. You can request a new verification link.');const csrf=csrfSession(req,res,user);res.json({user:{id:user.id,email:user.email,name:user.name,role:user.role,verified:true},csrf});});
 app.post('/api/auth/logout',(req,res)=>{db.prepare('DELETE FROM sessions WHERE hash=?').run(req.session.hash);res.clearCookie(cookieName,{httpOnly:true,secure:production,sameSite:'lax',path:'/'});res.json({ok:true});});
 for(const kind of ['reset','verify'])app.post('/api/auth/'+kind+'-request',(req,res)=>{mailReady();authLimit(req,kind+'-request',3);const user=db.prepare('SELECT * FROM users WHERE email=?').get(emailValue(req.body.email)||'');if(user&&(kind==='reset'||!user.verified))sendToken(user,kind);res.status(202).json({message:'If an eligible account matches this email, a link will arrive shortly.'});});
 app.post('/api/auth/verify',(req,res)=>{limited(db,'verify:'+digest(req.ip||''),30,900);const entry=db.prepare("SELECT * FROM tokens WHERE hash=? AND kind='verify' AND expires>?").get(digest(String(req.body.token||'')),Date.now());if(!entry)fail(400,'This link has expired or has already been used. Request another verification email.');transaction(db,()=>{db.prepare('UPDATE users SET verified=1 WHERE id=?').run(entry.user_id);db.prepare('DELETE FROM tokens WHERE hash=?').run(entry.hash);});res.json({message:'Email verified. You can now sign in.'});});
 app.post('/api/auth/reset',async(req,res)=>{limited(db,'reset:'+digest(req.ip||''),15,900);if(!validatePassword(req.body.password))fail(400,'Use a password of 15–256 characters.');const hash=await hashPassword(req.body.password);transaction(db,()=>{const entry=db.prepare("SELECT * FROM tokens WHERE hash=? AND kind='reset' AND expires>?").get(digest(String(req.body.token||'')),Date.now());if(!entry)fail(400,'This reset link has expired or has already been used.');db.prepare('UPDATE users SET password=?,verified=1 WHERE id=?').run(hash,entry.user_id);db.prepare('DELETE FROM tokens WHERE user_id=?').run(entry.user_id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(entry.user_id);audit(db,'password_reset',entry.user_id,null);});res.json({message:'Password updated. Sign in with your new password.'});});
 function quote(body){if(!Array.isArray(body.items)||!body.items.length||body.items.length>21)fail(400,'Your cart must contain 1–21 products.');const seen=new Set(),lines=[];
  for(const item of body.items){if(!item||typeof item.id!=='string'||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>99||seen.has(item.id))fail(400,'Invalid cart quantity or duplicate product.');seen.add(item.id);const p=db.prepare('SELECT * FROM products WHERE id=?').get(item.id);if(!p)fail(400,'Product not found.');if(p.stock===null||p.stock<item.quantity)fail(409,`${p.name} does not have sufficient confirmed stock.`);lines.push({id:p.id,name:p.name,strength:p.strength,price:p.price,quantity:item.quantity});}
  if(!body.address||typeof body.address!=='object')fail(400,'Enter a delivery address.');const a=body.address,address={name:field(a.name,'recipient name',100),line1:field(a.line1,'street address'),line2:a.line2?field(a.line2,'address line 2'): '',city:field(a.city,'city',100),region:field(a.region,'state / region',100),postal:field(a.postal,'postal code',30),country:field(a.country,'country',2).toUpperCase()};if(!config.countries.includes(address.country))fail(400,'Delivery is not available to this country.');
  const subtotal=lines.reduce((n,l)=>n+l.price*l.quantity,0),shipping=config.shipping,tax=config.taxMode==='included'?0:Math.round((subtotal+(config.taxShipping?shipping:0))*config.taxRate/10000);return {lines,address,subtotal,shipping,tax,total:subtotal+shipping+tax,currency:config.currency,taxIncluded:config.taxMode==='included'};
 }
 const checkoutReady=()=>{if(!readiness(config).ready)fail(503,'Checkout is not open yet. Please try again later.');};
 app.post('/api/quote',auth,(req,res)=>{checkoutReady();res.json(quote(req.body));});
 app.post('/api/orders',auth,(req,res)=>{checkoutReady();limited(db,'orders:'+req.session.user_id,30,3600);const method=req.body.method,key=req.get('Idempotency-Key');if(!['paypal','zelle'].includes(method)||!readiness(config)[method])fail(400,'This payment method is unavailable.');if(!key||!/^[a-zA-Z0-9-]{16,80}$/.test(key))fail(400,'A valid checkout request key is required.');const fingerprint=digest(JSON.stringify({items:req.body.items,address:req.body.address,method}));const order=transaction(db,()=>{const prior=db.prepare('SELECT * FROM orders WHERE user_id=? AND request_key=?').get(req.session.user_id,key);if(prior){if(prior.fingerprint!==fingerprint)fail(409,'This request key was already used for another checkout.');return prior;}const q=quote(req.body),id='AERO-'+randomUUID(),now=Date.now();for(const l of q.lines){const changed=db.prepare('UPDATE products SET stock=stock-?,version=version+1 WHERE id=? AND stock>=?').run(l.quantity,l.id,l.quantity);if(!changed.changes)fail(409,'Stock changed. Please review your cart.');}db.prepare('INSERT INTO orders(id,user_id,request_key,fingerprint,method,status,currency,subtotal,shipping,tax,total,lines,address,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,req.session.user_id,key,fingerprint,method,'Awaiting payment',q.currency,q.subtotal,q.shipping,q.tax,q.total,JSON.stringify(q.lines),JSON.stringify(q.address),now,now);audit(db,'order_created',req.session.user_id,id,method);queue(db,'created:'+id,req.session.email,`Order ${id} — awaiting payment`,`Your Aero Aminos order has been saved. It is not paid yet.\nTotal: ${q.currency} ${(q.total/100).toFixed(2)}\nView your order: ${config.origin}/#/orders\n${method==='zelle'?`Pay ${config.zelleName} at ${config.zelleRecipient} using Zelle. Include the complete order number in the memo. Payment will be verified before fulfillment.`:'Complete PayPal payment from your order page.'}`);return db.prepare('SELECT * FROM orders WHERE id=?').get(id);});res.status(201).json({order:publicOrder(order),...(method==='zelle'?{instructions:{recipient:config.zelleRecipient,name:config.zelleName,memo:order.id}}:{})});});
 app.get('/api/orders',auth,(req,res)=>{const page=Math.max(0,Math.min(10000,parseInt(req.query.page)||0));const list=req.session.role==='owner'?db.prepare('SELECT o.*,u.email,u.name FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created DESC,o.id LIMIT 51 OFFSET ?').all(page*50):db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY created DESC,id LIMIT 51 OFFSET ?').all(req.session.user_id,page*50);res.json({orders:list.slice(0,50).map(publicOrder),page,hasMore:list.length>50});});
 app.get('/api/orders/:id',auth,(req,res)=>{const order=orderFor(req,req.params.id);res.json({order:publicOrder(order),...(order.method==='zelle'&&order.status==='Awaiting payment'?{instructions:{recipient:config.zelleRecipient,name:config.zelleName,memo:order.id}}:{})});});
 async function locked(id,fn){if(locks.has(id))return locks.get(id);const promise=fn();locks.set(id,promise);try{return await promise;}finally{locks.delete(id);}}
 function validateProviderOrder(o,providerOrder){const unit=providerOrder.purchase_units?.[0];if(providerOrder.id!==o.paypal_id||providerOrder.purchase_units?.length!==1||unit.custom_id!==o.id||unit.payee?.merchant_id!==config.paypalMerchant||unit.amount?.currency_code!==o.currency||unit.amount.value!==(o.total/100).toFixed(2))fail(409,'Payment details require owner review.');return unit;}
 function completePayment(o,providerOrder){const unit=validateProviderOrder(o,providerOrder),capture=unit.payments?.captures?.[0];if(capture?.amount?.currency_code!==o.currency||capture.amount.value!==(o.total/100).toFixed(2)||!capture.id)fail(409,'Payment details require owner review.');
  if(capture.status!=='COMPLETED'){if(capture.status==='PENDING')db.prepare("UPDATE orders SET status='Pending',updated=? WHERE id=? AND status='Awaiting payment'").run(Date.now(),o.id);return false;}
  markPaid(o.id,'paypal',capture.id);return true;
 }
 function markPaid(id,actor,reference){transaction(db,()=>{const o=db.prepare('SELECT * FROM orders WHERE id=?').get(id);if(!o||!['Awaiting payment','Pending'].includes(o.status))return;db.prepare('UPDATE orders SET status=\'Paid\',payment_reference=?,capture_id=?,updated=? WHERE id=?').run(reference,o.method==='paypal'?reference:null,Date.now(),id);audit(db,'payment_confirmed',actor,id,reference);const u=db.prepare('SELECT * FROM users WHERE id=?').get(o.user_id);queue(db,'paid:customer:'+id,u.email,`Payment received — ${id}`,`Payment received for your Aero Aminos order.\nTotal: ${o.currency} ${(o.total/100).toFixed(2)}\nYour order is awaiting fulfillment.\n${config.origin}/#/orders`);queue(db,'paid:owner:'+id,config.ownerEmail,`Paid order — ${id}`,`${u.name} has a paid order ready for fulfillment.\n${config.origin}/#/orders`);});}
 app.post('/api/orders/:id/paypal',auth,async(req,res)=>{checkoutReady();if(!readiness(config).paypal)fail(503,'PayPal is unavailable.');const o=orderFor(req,req.params.id);if(o.method!=='paypal')fail(400,'Not a PayPal order.');if(!['Awaiting payment','Pending'].includes(o.status))fail(409,'This order is not awaiting payment.');const result=await locked(o.id,async()=>{const current=db.prepare('SELECT * FROM orders WHERE id=?').get(o.id);if(current.paypal_id)return {id:current.paypal_id};const response=await paypal.create(current);if(!response.id)throw new Error('PayPal order ID missing');db.prepare('UPDATE orders SET paypal_id=?,updated=? WHERE id=?').run(response.id,Date.now(),o.id);return {id:response.id};});res.json(result);});
 app.post('/api/orders/:id/capture',auth,async(req,res)=>{const o=orderFor(req,req.params.id);if(o.method!=='paypal'||!o.paypal_id)fail(400,'PayPal payment has not started.');await locked(o.id,async()=>{const current=db.prepare('SELECT * FROM orders WHERE id=?').get(o.id);if(!['Awaiting payment','Pending'].includes(current.status))return;let payment=await paypal.get(current.paypal_id);if(payment.status==='APPROVED'){checkoutReady();if(!readiness(config).paypal)fail(503,'PayPal is unavailable.');validateProviderOrder(current,payment);await paypal.capture(current.paypal_id);payment=await paypal.get(current.paypal_id);}if(!payment.purchase_units?.[0]?.payments?.captures?.length)fail(409,'Payment has not completed. Please finish PayPal checkout.');completePayment(current,payment);});res.json({order:publicOrder(db.prepare('SELECT * FROM orders WHERE id=?').get(o.id))});});
 app.post('/api/paypal/webhook',async(req,res)=>{if(!await paypal.verify(req.headers,req.body))fail(401,'Invalid webhook signature.');const e=req.body;if(typeof e.id!=='string'||typeof e.event_type!=='string')fail(400,'Invalid event.');if(db.prepare('SELECT id FROM webhooks WHERE id=?').get(e.id))return res.json({ok:true});
  const related=e.resource?.supplementary_data?.related_ids;let order=related?.order_id?db.prepare('SELECT * FROM orders WHERE paypal_id=?').get(related.order_id):null;
  if(e.event_type==='PAYMENT.CAPTURE.COMPLETED'&&order){const data=await paypal.get(order.paypal_id);completePayment(order,data);}
  else if(e.event_type==='PAYMENT.CAPTURE.REFUNDED'||e.event_type==='PAYMENT.CAPTURE.REVERSED'){
   const up=e.resource?.links?.find(x=>x.rel==='up')?.href||'';const captureId=related?.capture_id||(e.event_type==='PAYMENT.CAPTURE.REVERSED'?e.resource?.id:up.match(/\/v2\/payments\/captures\/([A-Za-z0-9]+)$/)?.[1]);order=db.prepare('SELECT * FROM orders WHERE capture_id=?').get(captureId||'');
   if(order){const amount=e.resource?.amount;if(!amount||amount.currency_code!==order.currency||!/^\d+\.\d{2}$/.test(amount.value))fail(400,'Invalid refund amount.');const cents=Math.round(Number(amount.value)*100);transaction(db,()=>{db.prepare('INSERT OR IGNORE INTO refunds(id,order_id,amount) VALUES(?,?,?)').run(e.resource.id,order.id,cents);const total=db.prepare('SELECT SUM(amount) AS amount FROM refunds WHERE order_id=?').get(order.id).amount;db.prepare('UPDATE orders SET status=?,updated=? WHERE id=?').run(total>=order.total?'Refunded':'Partially refunded',Date.now(),order.id);audit(db,'refund_recorded','paypal',order.id,e.id);});}
  }else if(e.event_type==='PAYMENT.CAPTURE.DENIED'&&order){db.prepare("UPDATE orders SET status='Payment failed',updated=? WHERE id=? AND status IN ('Awaiting payment','Pending')").run(Date.now(),order.id);audit(db,'payment_failed','paypal',order.id,e.id);}
  db.prepare('INSERT OR IGNORE INTO webhooks(id,event,created) VALUES(?,?,?)').run(e.id,e.event_type,Date.now());res.json({ok:true});
 });
 app.get('/api/owner/summary',owner,(_req,res)=>res.json({paidSubtotal:db.prepare("SELECT COALESCE(SUM(subtotal),0) AS n FROM orders WHERE status='Paid'").get().n,ready:db.prepare("SELECT COUNT(*) AS n FROM orders WHERE status='Paid' AND fulfillment='Unfulfilled'").get().n,pending:db.prepare("SELECT COUNT(*) AS n FROM orders WHERE status IN ('Awaiting payment','Pending')").get().n,orders:db.prepare('SELECT COUNT(*) AS n FROM orders').get().n,readiness:readiness(config),mail:db.prepare('SELECT status,COUNT(*) AS count FROM outbox GROUP BY status').all(),activity:db.prepare('SELECT event,order_id,detail,created FROM audit ORDER BY id DESC LIMIT 30').all()}));
 app.post('/api/owner/orders/:id/confirm-zelle',owner,async(req,res)=>{const o=orderFor(req,req.params.id);if(o.method!=='zelle'||o.status!=='Awaiting payment')fail(409,'Only unpaid Zelle orders can be confirmed.');if(req.body.confirmed!==true||req.body.amount!==o.total)fail(400,'Confirm that the full order amount has reached the business account.');const user=db.prepare('SELECT password FROM users WHERE id=?').get(req.session.user_id);limited(db,'owner-confirm:'+req.session.user_id,8,900);if(!await checkPassword(req.body.password,user.password))fail(403,'Owner password did not match.');const reference=field(req.body.reference,'bank transaction reference',100);if(db.prepare("SELECT id FROM orders WHERE method='zelle' AND payment_reference=?").get(reference))fail(409,'That bank reference has already been used.');markPaid(o.id,req.session.user_id,reference);res.json({order:publicOrder(db.prepare('SELECT * FROM orders WHERE id=?').get(o.id))});});
 app.post('/api/owner/orders/:id/cancel-zelle',owner,(req,res)=>{const o=orderFor(req,req.params.id);if(o.method!=='zelle'||o.status!=='Awaiting payment')fail(409,'Only unpaid Zelle orders can be canceled here.');transaction(db,()=>{db.prepare("UPDATE orders SET status='Canceled',updated=? WHERE id=?").run(Date.now(),o.id);for(const l of JSON.parse(o.lines))db.prepare('UPDATE products SET stock=stock+?,version=version+1 WHERE id=?').run(l.quantity,l.id);audit(db,'unpaid_order_canceled',req.session.user_id,o.id);});res.json({ok:true});});
 app.post('/api/owner/orders/:id/ship',owner,(req,res)=>{const o=orderFor(req,req.params.id);if(o.status!=='Paid'||o.fulfillment!=='Unfulfilled')fail(409,'Only paid, unfulfilled orders can be marked shipped.');const carrier=field(req.body.carrier,'carrier',80),tracking=field(req.body.tracking,'tracking number',100);transaction(db,()=>{db.prepare("UPDATE orders SET fulfillment='Shipped',tracking_carrier=?,tracking_number=?,updated=? WHERE id=?").run(carrier,tracking,Date.now(),o.id);audit(db,'order_shipped',req.session.user_id,o.id,carrier);const u=db.prepare('SELECT email FROM users WHERE id=?').get(o.user_id);queue(db,'shipped:'+o.id,u.email,`Your order has shipped — ${o.id}`,`Your Aero Aminos order has shipped.\nCarrier: ${carrier}\nTracking number: ${tracking}\n${config.origin}/#/orders`);});res.json({ok:true});});
 app.post('/api/owner/inventory/:id',owner,(req,res)=>{const stock=req.body.stock,version=req.body.version;if(!Number.isInteger(stock)||stock<0||stock>100000||!Number.isInteger(version))fail(400,'Enter a whole-number available stock quantity.');const result=db.prepare('UPDATE products SET stock=?,version=version+1 WHERE id=? AND version=?').run(stock,req.params.id,version);if(!result.changes)fail(409,'Inventory changed. Refresh before updating.');audit(db,'inventory_updated',req.session.user_id,null,`${req.params.id}: ${stock}`);res.json({ok:true});});
 app.use('/api',(_req,_res,next)=>next(Object.assign(new Error('Endpoint not found.'),{status:404})));
 app.use(express.static(resolve('dist'),{index:'index.html'}));
 app.use((error,_req,res,_next)=>{const status=error.status||(error.type==='entity.parse.failed'?400:500);if(status>=500)console.error(JSON.stringify({event:'request_failed',status}));res.status(status).json({error:status>=500?'This service is temporarily unavailable. Your order has not been marked paid.':error.message});});
 return {app,db,config,flushMail:mailWorker(db,config,transport)};
}
